# src\dashboard_service\docker-compose.yaml

version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dashboard_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - dashboard_network

volumes:
  mongodb_data:
    driver: local

networks:
  dashboard_network:
    driver: bridge
